name: pytorch-stardist
channels:
  - defaults
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python==3.7.9
  - pip==20.0.2
  - numpy==1.21.6
  - pandas==1.1.3
  - matplotlib==3.1.3
  - scipy==1.7.3
  - jupyter==1.0.0
  - tifffile==2020.6.3
  - pyyaml==6.0
  - tqdm==4.62.3
  - cudatoolkit=11.3
  - pytorch==1.10.2
  - torchvision==0.11.3
  - edt==2.3.0
  - pip:
    - gputools==0.2.13
    - numba==0.56.0
